version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack-full
    hostname: localstack
    networks:
      - localstack-net
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3,sqs,lambda,cloudformation,iam,cloudwatch,apigateway,events,logs,serverless
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=ndx
      - AWS_SECRET_ACCESS_KEY=ndx_secret
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
  
networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net